import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Providers from '@/store/providers'
import Script from 'next/script'
import { GoogleAnalytics } from '@next/third-parties/google'
import localFont from "next/font/local";

const inter = Inter({
  style: "normal",
  weight: ["300", "400", "700"],
  display: "auto",
  subsets: ["latin"],
  variable: "--font-inter",
});

const apple = localFont({
  src: [
    {
      path: "../../public/font/AppleGaramond-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/font/AppleGaramond.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/font/AppleGaramond-Light.ttf",
      weight: "300",
      style: "normal",
    },
  ],
  variable: "--font-apple",
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <Script
        src="https://platform-api.sharethis.com/js/sharethis.js#property=65d7025dafa82e0019c9e3e8&product=sop"
        async
      />
      <body style={{ ...inter.style }} className={`w-full ${apple.variable} font-sans`}>
        <Providers>{children}</Providers>
      </body>
      <GoogleAnalytics gaId="G-HPD8SMYT1T" />
    </html>
  )
}


