/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BuilderRouteRouteImport } from './routes/builder/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuilderIndexRouteImport } from './routes/builder/index'
import { Route as SlugIndexRouteImport } from './routes/$slug/index'
import { Route as BuilderSlugRouteImport } from './routes/builder/$slug'
import { Route as ApiUploadImageRouteImport } from './routes/api/upload-image'
import { Route as ApiGenerateContentRouteImport } from './routes/api/generate-content'

const BuilderRouteRoute = BuilderRouteRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderIndexRoute = BuilderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuilderRouteRoute,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/$slug/',
  path: '/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderSlugRoute = BuilderSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BuilderRouteRoute,
} as any)
const ApiUploadImageRoute = ApiUploadImageRouteImport.update({
  id: '/api/upload-image',
  path: '/api/upload-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateContentRoute = ApiGenerateContentRouteImport.update({
  id: '/api/generate-content',
  path: '/api/generate-content',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRouteRouteWithChildren
  '/api/generate-content': typeof ApiGenerateContentRoute
  '/api/upload-image': typeof ApiUploadImageRoute
  '/builder/$slug': typeof BuilderSlugRoute
  '/$slug': typeof SlugIndexRoute
  '/builder/': typeof BuilderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/generate-content': typeof ApiGenerateContentRoute
  '/api/upload-image': typeof ApiUploadImageRoute
  '/builder/$slug': typeof BuilderSlugRoute
  '/$slug': typeof SlugIndexRoute
  '/builder': typeof BuilderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builder': typeof BuilderRouteRouteWithChildren
  '/api/generate-content': typeof ApiGenerateContentRoute
  '/api/upload-image': typeof ApiUploadImageRoute
  '/builder/$slug': typeof BuilderSlugRoute
  '/$slug/': typeof SlugIndexRoute
  '/builder/': typeof BuilderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder'
    | '/api/generate-content'
    | '/api/upload-image'
    | '/builder/$slug'
    | '/$slug'
    | '/builder/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/generate-content'
    | '/api/upload-image'
    | '/builder/$slug'
    | '/$slug'
    | '/builder'
  id:
    | '__root__'
    | '/'
    | '/builder'
    | '/api/generate-content'
    | '/api/upload-image'
    | '/builder/$slug'
    | '/$slug/'
    | '/builder/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderRouteRoute: typeof BuilderRouteRouteWithChildren
  ApiGenerateContentRoute: typeof ApiGenerateContentRoute
  ApiUploadImageRoute: typeof ApiUploadImageRoute
  SlugIndexRoute: typeof SlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/': {
      id: '/builder/'
      path: '/'
      fullPath: '/builder/'
      preLoaderRoute: typeof BuilderIndexRouteImport
      parentRoute: typeof BuilderRouteRoute
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/$slug': {
      id: '/builder/$slug'
      path: '/$slug'
      fullPath: '/builder/$slug'
      preLoaderRoute: typeof BuilderSlugRouteImport
      parentRoute: typeof BuilderRouteRoute
    }
    '/api/upload-image': {
      id: '/api/upload-image'
      path: '/api/upload-image'
      fullPath: '/api/upload-image'
      preLoaderRoute: typeof ApiUploadImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-content': {
      id: '/api/generate-content'
      path: '/api/generate-content'
      fullPath: '/api/generate-content'
      preLoaderRoute: typeof ApiGenerateContentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BuilderRouteRouteChildren {
  BuilderSlugRoute: typeof BuilderSlugRoute
  BuilderIndexRoute: typeof BuilderIndexRoute
}

const BuilderRouteRouteChildren: BuilderRouteRouteChildren = {
  BuilderSlugRoute: BuilderSlugRoute,
  BuilderIndexRoute: BuilderIndexRoute,
}

const BuilderRouteRouteWithChildren = BuilderRouteRoute._addFileChildren(
  BuilderRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderRouteRoute: BuilderRouteRouteWithChildren,
  ApiGenerateContentRoute: ApiGenerateContentRoute,
  ApiUploadImageRoute: ApiUploadImageRoute,
  SlugIndexRoute: SlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
